language: java
jdk:
  - oraclejdk8
# we want the latest release of JDK8
addons:
  apt:
    packages:
      - oracle-java8-installer
install: 'if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then mvn --settings .build/deploy-settings.xml -DaltDeploymentRepository=snapshots::default::http://m2.neo4j.org/content/repositories/snapshots clean deploy ; else mvn clean verify ; fi'
script:
  - ./tools/grammar/src/main/shell/launch.sh ISO14977 cypher.xml > grammar/generated/cypher.ebnf
  - ./tools/grammar/src/main/shell/launch.sh Antlr4 cypher.xml > grammar/generated/Cypher.g4
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagrams -outputDir=grammar/generated/railroad/raw cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagramPages -outputDir=grammar/generated/railroad cypher.xml
deploy:
  provider: s3
  bucket: artifacts.opencypher.org
  skip_cleanup: true
  local-dir: grammar/generated
  acl: public_read
  access_key_id:
    secure: XrpFNqYDVUhtq2IPJJWRWcWY9z5zX1cTOAVI5dXoCaa0gVqZXtPcAKJRApaub3OfpRfgQcWNSQcMoqf3mouOlisiBSNCOe1gd3j+lwIUklpPdl1Wet32pRd6jIvn/nPVT4u0uc0w2isZXSfrvQRWk7jiOF72TbkF4zghS/QHAatGg9r6fJr+iyOzLc0tWFM9sSgvlm3yUH+ESvBfYrWhOGV578Lt66oZCU+GR63PxVvVaNEkGZVYbp0sRaAxg9osvYtVh2ffhutq4JL3uOK9h364Ho40VusuzWiXtOW1XIVwA1/y0JBuJmKZ+cci8jrrTrkwwKo1LBHPHnfYasuIlZbKctxmG7yHSPfAVqKSXk+e6gsTfeSaOmW/OrPWoYbPnjg86pqKoTLjbN5MpILbV6Qmxt2xJhAqPU8sOVtcmTvXaVRQlZhZDbs7GHXyJa/JpzArxGqj0ucRgAyaI47EmFR6AytcEWbrRPCjfLdbQS5CNdPNGi0NNicpuWY5OaeE6MjN8nwaDjBcpjP/82Oi0aup3cyGAAyjZKx+TSo7dXneN5fuGNeuWs425FqX9M34rvrLtxkUX/f6xfI2tm5R6Tsy1iT/6sm+syHeDPzOO7lf5n8Ca0VsXV+so6xd9Be4EBIyZVFqg2Nf6TzXmOSZKtcwJX8NLDeb8dzhPYBfP/8=
  secret_access_key:
    secure: NnfIaBhzlVfI1gDEtSuVMtkCgGlwv5gXCE9iYHZtgefVjeuHl0JN0/4HTQJpV6SdyE2E7YkccvxuP5vtnWLJOMC97BzGomT6gsyYoMw4A9rzzMve7L9i30YgYqsP+x081JdmuoRhtKfMSznBNcUamOYTryY2wOmDlRyBlWyPqVztLh906hhca+O1F67K2FSH8HRg9pT930xDJsoJtwSdnkKmA6IsZUoev1ChvNPq8vC3CYMHU5KRUOf0tOMb2dbUrRufvVH7k7VlZV1chnNYj33yRVaddT7ve0omcO0fcAs71caj+ri7pSArRdzwODBEjFdUGcpia1PKcTxnVPnsAPUi0hl+ciIJNEhrTbDKmKhrPRHQerd21biCg/xht5t9fkf+XbUL8XbA73SeIDYbCyGvFZyJggaCRGbH8hjaJFfzRpk+fryK6Acaxn+K0Cr0TvUPcE4IqU6sz2zYNoFv25bKONJWY0DgJMiJ3QpJyOizFUsyEe2KgKPVmdTxBlnMIDc11tpnIHE+EUeIx30wAvraQeA1ypchTnU1WztO3Vj3BMusbqsY+qFf/OnTF674ruaSFHPB73D4B0gaTfxET68+5a+Fpbb0p8zQXI+ddGt1rQoZEhPiWgFOOc58qtcn3oHiwI8B8FnKMiI/JIK8Wqnt+ja/FPGxYmlvwOQW11A=
  on:
    repo: opencypher/openCypher
