dist: trusty
language: java
jdk:
  - oraclejdk8
# we want the latest release of JDK8
addons:
  apt:
    packages:
      - oracle-java8-installer
install: 'if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then mvn --settings .build/deploy-settings.xml -DaltDeploymentRepository=snapshots::default::http://m2.neo4j.org/content/repositories/snapshots clean deploy ; else mvn clean verify ; fi'
script:
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagramPages -outputDir=grammar/generated/railroad cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagramPages --INCLUDE_LEGACY=true -outputDir=grammar/generated/legacy/railroad cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagrams -DRailRoadDiagrams.inlineNone=true -outputDir=grammar/generated/railroad/raw cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagrams --INCLUDE_LEGACY=true -DRailRoadDiagrams.inlineNone=true -outputDir=grammar/generated/legacy/railroad/raw cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh ISO14977 cypher.xml > grammar/generated/cypher.ebnf
  - ./tools/grammar/src/main/shell/launch.sh ISO14977 --INCLUDE_LEGACY=true cypher.xml > grammar/generated/legacy/cypher.ebnf
  - ./tools/grammar/src/main/shell/launch.sh Antlr4 cypher.xml > grammar/generated/Cypher.g4
  - ./tools/grammar/src/main/shell/launch.sh Antlr4 --INCLUDE_LEGACY=true cypher.xml > grammar/generated/legacy/Cypher.g4
deploy:
  provider: s3
  bucket: artifacts.opencypher.org
  skip_cleanup: true
  local-dir: grammar/generated
  acl: public_read
  access_key_id:
    secure: "q+TCeEfI/U2zDvfBxnMt9iV+KuR6o/PXwSY1grhe+Vj2oT9VvP/ECbF8D28FA4HEyJaVYh58WWV448fsZMUM9drGbCkRhPYmuaGySKh8QThK7Fo6NOoZeMmECOLa1vBOYWFmYQsPaLd0GGviQ6FrDe8Ojs8YxH4BM8KK5dCCZkjV7p/j+VuLilcQqBy/mNUpkurDPKbmuVoac1LymwghhdQn61vubdQKtjwvIUOyiMspRLRHLcuayHh+2kAvIlnBTsb30PmZkyA//2yAzaRWytMSWsUIOG25Me9SzBdxu2E9Vd3DZdVPl9a2CQ6idirx0f1BIjZOWfhVIowesxA11TtUkkKJmKDy0/p+d9DnKMElHoYmQ0DTxCBLzUdur8lgjWULQcueu4gP1UY6aXOso0h56UOCaaHjLCPoYzHXP/R45BmBbAWsfmE06oDTEuS05Ypu9TzZKhU8FPGPNrvMQ5Q+aa8o5Zk/9eRkNgpVCepjTeZ3w0+7w/QWiIrBH49vpo8WmLADLqEKHzHWHv8I80EsASGhP1Yek9TincA80/WZrGNvEXsbhAuktqkj8TfRmAYgrqZTyxokpnDDl5kafzv7knhhlnbf7iiM3Gqg0K5HdFcIBlmDU77JGXQrokacljdPfMfM/nrB4zKobAWcBjiKABj8sysyQ1c1Nsnw+wI="
  secret_access_key:
    secure: "ebun/ftwwXBMbwlUv+FAsocl0rxVnoeFopuSGpAbVD2GWK3IsjagjmTVpdkrjkUwc2kr9UUvhh4r136IAGFg0KuOzt7oOHTBc59fFMlG56/voZxhg4m292hx9ot2qnU9vvPfxLNHMjIfiA4c4unbkVaIPcDOYpBdk7ldb8xnO1Ju4n4P+9mRmp7N2Rt2/NPHNKRV7vb7agEd2HujGfWnbP3ptrFGoA8NFkEWWxD5tHgE+ovKiItXbw9cIci/O3A2ZOrkkloYiYsM5jPEhKHRCzGO09HmsLhO2+CG8cecItkWFiHISBdaWZieRw5ctaSpZrECtZDTkg1zP7HjnswSRiPJOFIHTJunkboJRvSOjQNx8Xied3EsERD3ithxjt1JiCDYrC10Mdzx4jbsgUbY0e34TTfjudK8rhrGTUNn88sRIE0lCUnu/K76NPISG8N72L16BiThIuRorEGP0d/HWoBRtCV9ScQpVLoyWKD5Y2xI0r87oky+B42WHZHtQTZ6pErZtvhDdoMRLoOFi0j7Vj9qV+PeBN83VqsO+3nUKepS18v+PfUwAGNs8Yc119GQSEyNwabebwbaSwxNZN3gqkjkMeMyBnjVDxmObuu3Biy657CGEUrohqOlxjSNLK/017eMy/IvzRQ9g1thBdHIlBBnlNeerSj9V77qzlexjIE="
  on:
    repo: opencypher/openCypher
