dist: trusty
language: java
jdk:
  - oraclejdk8
# we want the latest release of JDK8
addons:
  apt:
    packages:
      - oracle-java8-installer
install: 'mvn clean verify'
script:
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagramPages -outputDir=grammar/generated/railroad cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagramPages --INCLUDE_LEGACY=true -outputDir=grammar/generated/legacy/railroad cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagrams -DRailRoadDiagrams.inlineNone=true -outputDir=grammar/generated/railroad/raw cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh RailRoadDiagrams --INCLUDE_LEGACY=true -DRailRoadDiagrams.inlineNone=true -outputDir=grammar/generated/legacy/railroad/raw cypher.xml
  - ./tools/grammar/src/main/shell/launch.sh ISO14977 cypher.xml > grammar/generated/cypher.ebnf
  - ./tools/grammar/src/main/shell/launch.sh ISO14977 --INCLUDE_LEGACY=true cypher.xml > grammar/generated/legacy/cypher.ebnf
  - ./tools/grammar/src/main/shell/launch.sh Antlr4 cypher.xml > grammar/generated/Cypher.g4
  - ./tools/grammar/src/main/shell/launch.sh Antlr4 --INCLUDE_LEGACY=true cypher.xml > grammar/generated/legacy/Cypher.g4
deploy:
  provider: s3
  bucket: artifacts.opencypher.org
  skip_cleanup: true
  local-dir: grammar/generated
  acl: public_read
  access_key_id:
    secure: ZjbOdaO6wa5zhbXesAHiaUEb1bB2xk9yThyN32Ek9HuRJTU/tBKqI+YM0rhenBC7WLzyUbVg2NHWh+xLz5j2vdmcNA0gr0Y3Eja7oQBydrPqIRF8cLSuEvxqgqvnVFadtzrYfvmvtKgLxxFsX4wEJEkdPfGS0iCiJhajqqJnE1Sys0sPXei+C+r7uHq0qitCq88G9/lt8x+c9bm3p2YKcBbGxPN83p1vAgAXI03fD8MscIeO/1LS7CqQIF1Sj2K8BetqSsKUJP+3wXtQ3/b/hX/sP5Oqbb/uXlsu0j6WnS+mnPBbICgcB9wixTm0tLMyfZex2Je5ux5I87dzhBq0XsDI3CEk8muO4tZcMZpv8m/Cpg9n+m+3INH5WcL9V/fLRuF+9yxvTctFz5R/8YsFT10u1nbii7XYK29R2SCQzKIA1AGHg9AH4TEIZx5A0txtxg+9rCHh/gLhSscJAEjBiBBzu1R+BPMxdP9BNn7sNGc9pihgu7zSLWs7UmvpYqvbzGJ0tyAgpmAHwKISsI/bFE+X+fk04XEZb0uC9FxGnAY6NDezhrkHUasyk0m5/d9lURpCBeapGWqrgIvVtu2/OAy+eZ/A8wkyx2L3AY9VMzleIG6sBJi/soQPc95gJ1RQppQPHPbmVue52U9ePod4NFPKYtD/uEcUce1Mg8hEbkw=
  secret_access_key:
    secure: D2cb+7hRwWbcJENm2JI2CQARAeA53uVDcdZInjji+CK5Hjo3rva+ZTz07yqlzgHmBjw16oNlkSlzniTE+FKGPEMU47lxG0gEZvZBUxU1CMDCihTRbox6gHlXzwb7QjS8BH4ns5NcPMuQ0sX/8T0ky5aO6qYmcRZyUKvAti8i3qmMLgLyMANsIf3RWrBg4SaYF+KvXkrqY85cGEpEZod3o3xsYbJaYZXW7Lx1UAErh8POKPrIZ4a1W8N24CfcZFLrVdcJkr/OWy6dHQ17A/bj38h83bw3gV5dx64R5sfS5HGrK0zdybCungKaYEF99d8Num9wbjbJGEZ7hzve976oiEk6kGJKHPoUG0VBzqeuAcPKtZ+evxFPuMm7GORCSVlsuM1VGjK0Lj3V+rTt27/ElMqc0IO1OhDm8o5OiHEii4+FTtG3vpHUpY8/tumGE3DTtNSMi0WrP6MXIFwojLyMXXHVhJ5kYiojzm/JarQh1bKuaetj9LpN4rzJojbQOaNtCqyrxT/5nTdieb3emrenBKAHjAUg9+JCmZCvdQCORFjHqQiq5/2bacMSvCEKRT6HEea6cUm9qlIZm+hpRZNmyJcCFiPUe6wE//k7oJpEKf4EgDc0ELvCZJPNumN0vM8nfR4tWE6MMEEwiwWkOV1cHZyi9ivXWj3kBBxbi2Cpv5w=
  on:
    repo: opencypher/openCypher
